# -*- coding: utf-8 -*-
"""Final project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvUHnHCiHRJXeWLplzdsBoMuvY601eWX
"""

from google.colab import drive
drive.mount('/content/drive')

import os

TEXT_FOLDER = "/content/drive/MyDrive/poetry_project"

files = sorted([f for f in os.listdir(TEXT_FOLDER) if f.endswith(".txt")])

print(files)
print(f"\nعدد الملفات: {len(files)}")

!pip install -q groq

import os
import json
from groq import Groq

# ضع API KEY هنا
client = Groq(
    api_key=""
)

# مجلد النصوص
TEXT_FOLDER = "/content/drive/MyDrive/poetry_project"

# ملف الحفظ النهائي
OUTPUT_FILE = "/content/drive/MyDrive/poetry_project/dataset_scenarios.json"

dataset = []

# التعليمات
SYSTEM_PROMPT = """
🛑 التزم حرفياً بالنص المرفق فقط.
🛑 يُمنع منعاً باتاً التأليف أو التخمين أو إعادة الصياغة.
🛑 لا تضف أي معلومة غير موجودة في النص.
🛑 إذا لم تجد scenario واضح لا تنشئ عينة.

المطلوب:

استخرج:
- scenario = الحالة أو الوصف أو الموقف كما ورد حرفياً بالنص.
- poem phrase = البيت الشعري المرتبط بهذه الحالة فقط.

صيغة الإخراج:

[
  {
    "input": "scenario",
    "output": "poem phrase"
  }
]

مثال:

{
  "input": "إذا رأى ذا مودة قد حال عما عهده",
  "output": "ليس الخليلُ على ما كنتُ تعهَدُه   قد بَدَّلَ الله ذاكَ الخِلَّ ألوانا"
}

أعد JSON فقط.
"""

# قراءة الملفات
files = sorted([f for f in os.listdir(TEXT_FOLDER) if f.endswith(".txt")])

for file_name in files:

    file_path = os.path.join(TEXT_FOLDER, file_name)

    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    try:

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": text
                }
            ],
            temperature=0
        )

        result = response.choices[0].message.content.strip()

        # تنظيف الرد
        result = result.replace("```json", "")
        result = result.replace("```", "")
        result = result.strip()

        samples = json.loads(result)

        dataset.extend(samples)

        print(f"تمت معالجة: {file_name} | عدد العينات: {len(samples)}")

    except Exception as e:
        print(f"خطأ في {file_name}: {e}")

# حفظ الملف النهائي
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    json.dump(dataset, f, ensure_ascii=False, indent=2)

print("\nتم إنشاء dataset_scenarios.json ✅")
print("إجمالي العينات:", len(dataset))

import json
import random

DATASET_PATH = "/content/drive/MyDrive/poetry_project/dataset_scenarios.json"

# قراءة البيانات
with open(DATASET_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

# عدد العينات
print("عدد العينات:", len(data))

# عرض عينات عشوائية
print("\nعينات عشوائية:\n")

samples = random.sample(data, min(10, len(data)))

for sample in samples:

    print("INPUT:")
    print(sample["input"])

    print("\nOUTPUT:")
    print(sample["output"])

    print("\n" + "="*70 + "\n")